version: "3.8"

services:
    app:
        image: php:8.1-fpm
        container_name: laravel_app
        volumes:
            - ./:/var/www/html
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        working_dir: /var/www/html
        environment:
            - PHP_EXTENSION=pdo_pgsql
        networks:
            - laravel_network
        depends_on:
            - postgres

    web:
        image: nginx:alpine
        container_name: laravel_web
        volumes:
            - ./:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/snippets/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf

        ports:
            - "8084:80"
        networks:
            - laravel_network
        depends_on:
            - app

    postgres:
        image: postgres:13
        container_name: laravel_postgres
        environment:
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: news
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel_network

    adminer:
        image: adminer
        container_name: adminer
        ports:
            - 8081:8080
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

volumes:
    pgdata:
