version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /var/www/html
    environment:
      - PHP_EXTENSION=pdo_pgsql
    networks:
      - zaharie-assessment_laravel_network
    depends_on:
      - postgres
    ports:
      - "3000:8000" 
    command: ["sh", "-c", "cron && php-fpm"] 

  postgres:
    image: postgres:13
    container_name: laravel_postgres
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: news
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - zaharie-assessment_laravel_network

networks:
  zaharie-assessment_laravel_network:
    driver: bridge

volumes:
  pgdata:
